basedev/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apprest.urls import router, urls2, urls3, urls4, urls5, urlsToken
from django.conf import settings

admin.autodiscover()
 
urlpatterns = patterns('',    
    url(r'^', include('main.urls', namespace="main")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^api/rest/', include(router.urls, namespace="rest")),
    url(r'^api/rest/', include(urls2, namespace="rest2")),
    url(r'^api/rest/', include(urls3, namespace="rest3")),
    url(r'^api/rest/', include(urls4, namespace="rest4")),
    url(r'^api/rest/', include(urls5, namespace="rest5")),
    url(r'^api/rest/', include(urlsToken, namespace="token")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')), 
    url(r'^admin/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls import url

from . import views, viewPdf, html2pdf, viewPdf2
from viewPdf2 import hello_pdf_5, hello_pdf_6

urlpatterns = [
    # ex: / 
    url(r'^$', views.index, name='index'),
    # ex: /5/
    url(r'^(?P<_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /5/results/
    url(r'^results/(?P<qid>[0-9]+)/$', views.results, name='results'),
    # ex: 5/vote/
    url(r'^vote/(?P<id>[0-9]+)/$', views.vote, name='vote'),

    url(r'^report/pdf$', viewPdf.generatePdf, name='getPdf'),

    url(r'^report/pdf/bytes$', viewPdf.generatePdfBytes, name='getPdfBytes'),

    url(r'^report/html2pdf$', html2pdf.convert, name='html2pdf'),

    url(r"^hello/pdf$", viewPdf2.HelloPDFView.as_view(), name='getPdf2'),

    url(r"^hello/pdf2$", viewPdf2.HelloPDFView2.as_view(), name='getPdf3'),

    url(r"^hello/pdf3$", viewPdf2.HelloPDFView3.as_view(), name='getPdf4'),

    url(r"^hello/pdf4$", viewPdf2.HelloPDFView4.as_view(), name='getPdf5'),

    url(r"^hello/pdf5$", hello_pdf_5, name='getPdf6'),

    url(r"^hello/pdf6$", hello_pdf_6, name='getPdf7'),
]

polls/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/home/
    url(r'^home$', views.homepage, name='home'),
    # /polls/report/line
    url(r'^report/line', TemplateView.as_view(template_name='polls/line.html'), name='line'),
    # /polls/report/column
    url(r'^report/column', TemplateView.as_view(template_name='report/column.html'), name='column'),
    # /polls/report/pie
    url(r'^report/pie', TemplateView.as_view(template_name='pie.html'), name='pie'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):              # __str__ on Python 3
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):              # __str__ on Python 3
        return self.choice_text

class Test(models.Model):
    # id = models.AutoField(primary_key=True) # django lo crea automaticamente sino se especifica un primary_key
    iden = models.IntegerField(primary_key=True)
    code = models.CharField(max_length=4, unique=True)
    name = models.CharField(max_length=50, db_column='fullname')
    period = models.CharField(max_length=6, db_index=True)
    dni = models.CharField(max_length=8, blank=True)
    email = models.EmailField(max_length=75, null=True)
    comments = models.TextField(null=True)
    num = models.IntegerField(default=0, null=True)
    cost = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    vent = models.DecimalField(max_digits=13, decimal_places=4, null=True)
    total = models.FloatField(null=True)
    sec = models.SmallIntegerField(null=True)
    big = models.BigIntegerField(null=True)
    flag = models.NullBooleanField()
    active = models.BooleanField(default=True)
    cum_date = models.DateField(null=True)
    reg_date = models.DateTimeField(auto_now_add=True, null=True)
    reg_user = models.CharField(max_length=30, null=True)
    mod_date = models.DateTimeField(auto_now=True, null=True)
    mod_user = models.CharField(max_length=30, null=True)

    def __unicode__(self):              # __str__ on Python 3
        return "{0} {1}".format(self.code, self.name)

polls/views.py
#from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext

from .models import Choice, Question

import logging
logger = logging.getLogger(__name__)

def homepage(request):
    """
    Shows the homepage with a welcome message that is translated in the
    user's language.
    """
    message = ugettext('Welcome to our site!')
    return render(request, 'polls/homepage.html', {'message': message})

#@login_required # se debe crear el path /accounts/login/
def index(request):

    ## test de logger
    logger.debug('test de debug...........')
    # logger.info('test de info...........')
    # logger.warning('test de warn...........')
    # logger.error('test de error...........')
    # logger.critical('test de critical...........')

    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context) # busca en el file: /polls/templates/index.html

def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request, 'polls/detail.html', {'question': question})
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

templates/polls/detail.html
{% extends "base.html" %}

{% block title %}Detail - Polls{% endblock %}

{% block content %}
   <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>

{% endblock %}

templates/polls/homepage.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans 'Homepage - Hall of Fame' %}{% endblock %}

{% block content %}
    {# Translated in the view: #}
    <h1>{{ message }}</h1>
    <p>
      {% blocktrans count member_count=bands.count %}
      Here is the only band in the hall of fame:
      {% plural %}
      Here are all the {{ member_count }} bands in the hall of fame:
      {% endblocktrans %}
    </p>
    <ul>
    {% for band in bands %}
      <li>
        <h2><a href="{{ band.get_absolute_url }}">{{ band.name }}</a></h2>
        {% if band.can_rock %}<p>{% trans 'This band can rock!' %}</p>{% endif %}
      </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/polls/index.html
{% extends "base.html" %}

{% block title %}Index - Polls{% endblock %}

{% block content %}
    <h1>HOME</h1>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            {% comment "Optional note" %}
                <p>Commented out text with {{ create_date|date:"c" }}</p>
            {% endcomment %}
            <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
            {# <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> #}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <br/>
    <div>
        <h3>Main</h3>
        <ul>
            <li><a href="{% url 'main:index' %}">Index</a></li>
            <li><a href="{% url 'main:detail' 1 %}">Detalle</a></li>
            <li><a href="{% url 'main:results' 2 %}">Result</a></li>
            <li><a href="{% url 'main:vote' 3 %}">Vote</a></li>
            <li><a href="{% url 'main:getPdf' %}">PDF</a></li>
            <li><a href="{% url 'main:getPdfBytes' %}">PDFB</a></li>
            <li><a href="{% url 'main:html2pdf' %}">Htlm2Pdf</a></li>
            <li><a href="{% url 'main:getPdf2' %}">PDF2</a></li>
        </ul>
    </div>  
    <br/>
    <div>
        <h3>Api rest</h3>
        <ul>
            <li><a href="{% url 'rest:libro-list' %}">Libros</a></li>
            <li><a href="{% url 'rest:autor-list' %}">Autor</a></li>
            <li><a href="{% url 'rest:file-list' %}">File</a></li>
            <li><a href="{% url 'rest2:my_rest_view_1' 2 %}">my_rest_view_1</a></li>
            <li><a href="{% url 'rest2:my_rest_view_1' 3 %}?format=json&arg1=128&arg2=hola">my_rest_view_1 2</a></li>
            <li><a href="{% url 'rest2:my_rest_view_1' 70 %}/?format=json&arg1=128&arg2=hola">my_rest_view_1 3</a></li>
            <li><a href="{% url 'rest2:my_rest_view_2' %}">my_rest_view_2</a></li>
            <li><a href="{% url 'rest2:my_rest_view_2' %}?code=00198&active=true">my_rest_view_2 params</a></li>
            <li><a href="{% url 'rest3:my_json_1' n1=5 %}">json_1</a></li>
            <li><a href="{% url 'rest3:my_json_2' n1=5 n2=2 %}">json_2</a></li>
            <li><a href="{% url 'rest3:my_json_3' n1=5 n2=2 %}">json_3</a></li>
            <li><a href="{% url 'rest3:my_json_4' p1=1 p2=2 p3=3 %}">json_4</a></li>
            <li><a href="{% url 'rest3:my_json_5' m1=1091 m2=2245 m3=09 %}">json_5</a></li>
            <li><a href="{% url 'rest3:my_json_5' 1091 2245 09 %}">json_5 withou param names</a></li>
            <li><a href="{% url 'rest4:base_file' %}">Base File</a></li>
            <li><a href="{% url 'rest4:base_file_pk' 2 %}">Base File PK</a></li>
            <li><a href="{% url 'rest5:api_files' %}">Api Files</a></li>
            <li><a href="{% url 'rest5:api_file' 2 %}">Api File</a></li>
        </ul>
    </div>  
    <br/>
    <div>
        <h3>Reportes</h3>
        <ul>
            <li><a href="{% url 'polls:line' %}">Line</a></li>
            <li><a href="{% url 'polls:column' %}">Column</a></li>
            <li><a href="{% url 'polls:pie' %}">Pie</a></li>
        </ul>
    </div>  
{% endblock %}

templates/polls/line.html
{% extends "base.html" %}

{% block title %}Line Report{% endblock %}

{% load staticfiles %}

{% block content %}
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
{% endblock %}

{% block scriptbody %}
    <script src="{% static 'js/libs/highcharts.js' %}"></script>
    <script src="{% static 'js/libs/exporting.js' %}"></script>
    <script>
        $(function () {
            $('#container').highcharts({
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Monthly Average Temperature'
                },
                subtitle: {
                    text: 'Source: WorldClimate.com'
                },
                xAxis: {
                    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                },
                yAxis: {
                    title: {
                        text: 'Temperature (°C)'
                    }
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                },
                series: [{
                    name: 'Tokyo',
                    data: [7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
                }, {
                    name: 'London',
                    data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
                }]
            });
        });
       
    </script>
{% endblock %}

templates/polls/results.html
{% extends "base.html" %}

{% block title %}Results - Polls{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}